export const HIDE_VIEW_CART_MODAL = "HIDE_VIEW_CART_MODAL";
export const SHOW_VIEW_CART_MODAL = "SHOW_VIEW_CART_MODAL";

export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";

export const HIDE_REGISTER_MODAL = "HIDE_REGISTER_MODAL";
export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL";

export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_LOADING = "ADD_PRODUCT_REVIEW_LOADING";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAILURE = "ADD_PRODUCT_REVIEW_FAILURE";

export const GET_PRODUCT_REVIEW_REQUEST = "GET_PRODUCT_REVIEW_REQUEST";
export const GET_PRODUCT_REVIEW_LOADING = "GET_PRODUCT_REVIEW_LOADING";
export const GET_PRODUCT_REVIEW_SUCCESS = "GET_PRODUCT_REVIEW_SUCCESS";
export const GET_PRODUCT_REVIEW_FAILURE = "GET_PRODUCT_REVIEW_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_LOADING = "GET_PRODUCT_BY_ID_LOADING";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_POPULAR_PRODUCTS_REQUEST = "GET_POPULAR_PRODUCTS_REQUEST";
export const GET_POPULAR_PRODUCTS_LOADING = "GET_POPULAR_PRODUCTS_LOADING";
export const GET_POPULAR_PRODUCTS_SUCCESS = "GET_POPULAR_PRODUCTS_SUCCESS";
export const GET_POPULAR_PRODUCTS_FAILURE = "GET_POPULAR_PRODUCTS_FAILURE";

export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_LOADING = "GET_DEPARTMENTS_LOADING";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const USER_LOADING = "USER_LOADING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";


export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_DEPARTMENT_REQUEST = "GET_PRODUCTS_BY_DEPARTMENT_REQUEST";


