export const HIDE_VIEW_CART_MODAL = "HIDE_VIEW_CART_MODAL";
export const SHOW_VIEW_CART_MODAL = "SHOW_VIEW_CART_MODAL";

export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";

export const HIDE_REGISTER_MODAL = "HIDE_REGISTER_MODAL";
export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_POPULAR_PRODUCTS_REQUEST = "GET_POPULAR_PRODUCTS_REQUEST";
export const GET_POPULAR_PRODUCTS_LOADING = "GET_POPULAR_PRODUCTS_LOADING";
export const GET_POPULAR_PRODUCTS_SUCCESS = "GET_POPULAR_PRODUCTS_SUCCESS";
export const GET_POPULAR_PRODUCTS_FAILURE = "GET_POPULAR_PRODUCTS_FAILURE";

export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";


