export const HIDE_VIEW_CART_MODAL = "HIDE_VIEW_CART_MODAL";
export const SHOW_VIEW_CART_MODAL = "SHOW_VIEW_CART_MODAL";

export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";

export const HIDE_REGISTER_MODAL = "HIDE_REGISTER_MODAL";
export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL";

export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_LOADING = "ADD_PRODUCT_REVIEW_LOADING";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAILURE = "ADD_PRODUCT_REVIEW_FAILURE";

export const GET_PRODUCT_REVIEW_REQUEST = "GET_PRODUCT_REVIEW_REQUEST";
export const GET_PRODUCT_REVIEW_LOADING = "GET_PRODUCT_REVIEW_LOADING";
export const GET_PRODUCT_REVIEW_SUCCESS = "GET_PRODUCT_REVIEW_SUCCESS";
export const GET_PRODUCT_REVIEW_FAILURE = "GET_PRODUCT_REVIEW_FAILURE";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_LOADING = "GET_PRODUCT_BY_ID_LOADING";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAILURE = "GET_PRODUCT_BY_ID_FAILURE";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const GET_POPULAR_PRODUCTS_REQUEST = "GET_POPULAR_PRODUCTS_REQUEST";
export const GET_POPULAR_PRODUCTS_LOADING = "GET_POPULAR_PRODUCTS_LOADING";
export const GET_POPULAR_PRODUCTS_SUCCESS = "GET_POPULAR_PRODUCTS_SUCCESS";
export const GET_POPULAR_PRODUCTS_FAILURE = "GET_POPULAR_PRODUCTS_FAILURE";

export const GET_DEPARTMENTS_REQUEST = "GET_DEPARTMENTS_REQUEST";
export const GET_DEPARTMENTS_LOADING = "GET_DEPARTMENTS_LOADING";
export const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
export const GET_DEPARTMENTS_FAILURE = "GET_DEPARTMENTS_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CART_AMOUNT_REQUEST = "GET_CART_AMOUNT_REQUEST";
export const GET_CART_AMOUNT_LOADING = "GET_CART_AMOUNT_LOADING";
export const GET_CART_AMOUNT_SUCCESS = "GET_CART_AMOUNT_SUCCESS";
export const GET_CART_AMOUNT_FAILURE = "GET_CART_AMOUNT_FAILURE";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_LOADING = "DELETE_CART_ITEM_LOADING";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_LOADING = "ADD_CART_LOADING";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILURE = "ADD_CART_FAILURE";

export const EMPTY_CART = "EMPTY_CART";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_LOADING = "UPDATE_CART_LOADING";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const USER_LOADING = "USER_LOADING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_SHIPPING_REGION_LOADING = "GET_SHIPPING_REGION_LOADING";
export const GET_SHIPPING_REGION_SUCCESS = "GET_SHIPPING_REGION_SUCCESS";
export const GET_SHIPPING_REGION_FAILURE = "GET_SHIPPING_REGION_FAILURE";
export const GET_SHIPPING_REGION_REQUEST = "GET_SHIPPING_REGION_REQUEST";

export const GET_SHIPPING_REGION_BY_ID_LOADING = "GET_SHIPPING_REGION_BY_ID_LOADING";
export const GET_SHIPPING_REGION_BY_ID_SUCCESS = "GET_SHIPPING_REGION_BY_ID_SUCCESS";
export const GET_SHIPPING_REGION_BY_ID_FAILURE = "GET_SHIPPING_REGION_BY_ID_FAILURE";
export const GET_SHIPPING_REGION_BY_ID_REQUEST = "GET_SHIPPING_REGION_BY_ID_REQUEST";

export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";

export const GET_TAX_LOADING = "GET_TAX_LOADING";
export const GET_TAX_SUCCESS = "GET_TAX_SUCCESS";
export const GET_TAX_FAILURE = "GET_TAX_FAILURE";
export const GET_TAX_REQUEST = "GET_TAX_REQUEST";

export const CREATE_STRIPE_CHARGE_LOADING = "CREATE_STRIPE_CHARGE_LOADING";
export const CREATE_STRIPE_CHARGE_SUCCESS = "CREATE_STRIPE_CHARGE_SUCCESS";
export const CREATE_STRIPE_CHARGE_FAILURE = "CREATE_STRIPE_CHARGE_FAILURE";
export const CREATE_STRIPE_CHARGE_REQUEST = "CREATE_STRIPE_CHARGE_REQUEST";

export const GEN_STRIPE_TOKEN_LOADING = "GEN_STRIPE_TOKEN_LOADING";
export const GEN_STRIPE_TOKEN_SUCCESS = "GEN_STRIPE_TOKEN_SUCCESS";
export const GEN_STRIPE_TOKEN_FAILURE = "GEN_STRIPE_TOKEN_FAILURE";
export const GEN_STRIPE_TOKEN_REQUEST = "GEN_STRIPE_TOKEN_REQUEST";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const ADDRESS_REQUEST = "ADDRESS_REQUEST";
export const USER_REQUEST = "USER_REQUEST";


export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST";
export const GET_PRODUCTS_BY_DEPARTMENT_REQUEST = "GET_PRODUCTS_BY_DEPARTMENT_REQUEST";


